---
title: "Table 3: EF_calculation"
author: "Xiaolei"
date: "24/07/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
setwd("./")
source("../../src/ef_ci.R")

load("../../../data/cardiomyopathy/cohort_variant_count.RData")
load("../../../data/cardiomyopathy/prediction/cm_prediction.RData")

patient_number<-5665
gnomAD_number<-138632
```



```{r EF_raw, include=FALSE}
## EF raw with priorization information
#have the case freq and control freq for each missense variant seen in SHaRe
gene_list<-unique(variant_count$gene)
EF_raw=data.frame(gene=gene_list)
case_freq_gene<-aggregate(case_freq~gene,data=variant_count,sum)
EF_raw$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$gene),]$case_freq


gnomAD_freq_gene<-aggregate(gnomAD_AF~gene,data=cm_prediction,sum)
EF_raw$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$gene),]$gnomAD_AF

EF_raw[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(EF_raw[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2])}))
EF_raw$EF<-ef(EF_raw$case_freq_gene,EF_raw$gnomAD_freq_gene,predict="raw")


EF_raw$ci_lower<-ef_ci_lower(EF_raw$case_freq_gene,EF_raw$gnomAD_freq_gene,patient_number,gnomAD_number,predict = "raw")
EF_raw$ci_upper<-ef_ci_upper(EF_raw$case_freq_gene,EF_raw$gnomAD_freq_gene,patient_number,gnomAD_number,predict="raw")

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")


EF_raw[,2:6]<-round(EF_raw[,2:6],2)

```

```{r pathogenic, include=FALSE}
## EF with CardioBoost Pathogenic predictions
EF_patho=data.frame(gene=gene_list)

case_freq_gene<-aggregate(case_freq~gene,data=subset(variant_count,pathogenicity>=0.9),sum)
EF_patho$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$gene),]$case_freq
EF_patho$case_freq_gene<-ifelse(is.na(EF_patho$case_freq_gene),0,EF_patho$case_freq_gene)

gnomAD_freq_gene<-aggregate(gnomAD_AF~gene,data=subset(cm_prediction,pathogenicity>=0.9),sum)
EF_patho$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$gene),]$gnomAD_AF
EF_patho$gnomAD_freq_gene<-ifelse(is.na(EF_patho$gnomAD_freq_gene),0,EF_patho$gnomAD_freq_gene)

EF_patho[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(EF_patho[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2])}))
EF_patho$EF<-ef(EF_patho$case_freq_gene,EF_patho$gnomAD_freq_gene,predict="pathogenic")

EF_patho$ci_lower<-ef_ci_lower(EF_patho$case_freq_gene,EF_patho$gnomAD_freq_gene,patient_number,gnomAD_number,predict="pathogenic")
EF_patho$ci_upper<-ef_ci_upper(EF_patho$case_freq_gene,EF_patho$gnomAD_freq_gene,patient_number,gnomAD_number,predict="pathogenic")

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

EF_patho[,2:6]<-round(EF_patho[,2:6],2)

```


```{r pathogenic_novel, include=FALSE}
## EF with CardioBoost pathogenic prediction excluding the ones seen in training data

EF_patho_novel=data.frame(gene=gene_list)

case_freq_gene<-aggregate(case_freq~gene,data=subset(variant_count,pathogenicity>=0.9 & isTrain==FALSE),sum)
EF_patho_novel$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$gene),]$case_freq
EF_patho_novel$case_freq_gene<-ifelse(is.na(EF_patho_novel$case_freq_gene),0,EF_patho_novel$case_freq_gene)


gnomAD_freq_gene<-aggregate(gnomAD_AF~gene,data=subset(cm_prediction,pathogenicity>=0.9 & isTrain==FALSE),sum)
EF_patho_novel$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$gene),]$gnomAD_AF
EF_patho_novel$gnomAD_freq_gene<-ifelse(is.na(EF_patho_novel$gnomAD_freq_gene),0,EF_patho_novel$gnomAD_freq_gene)

EF_patho_novel[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(EF_patho_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2])}))
EF_patho_novel$EF<-ef(EF_patho_novel$case_freq_gene,EF_patho_novel$gnomAD_freq_gene,predict="pathogenic")


EF_patho_novel$ci_lower<-ef_ci_lower(EF_patho_novel$case_freq_gene,EF_patho_novel$gnomAD_freq_gene,patient_number,gnomAD_number,predict="pathogenic")
EF_patho_novel$ci_upper<-ef_ci_upper(EF_patho_novel$case_freq_gene,EF_patho_novel$gnomAD_freq_gene,patient_number,gnomAD_number,predict="pathogenic")

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

EF_patho_novel[,2:6]<-round(EF_patho_novel[,2:6],2)
```


```{r, include=FALSE}

## EF with CardioBoost benign prediction
EF_benign=data.frame(gene=gene_list)

case_freq_gene<-aggregate(case_freq~gene,data=subset(variant_count,pathogenicity<=0.1 ),sum)
EF_benign$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$gene),]$case_freq
EF_benign$case_freq_gene<-ifelse(is.na(EF_benign$case_freq_gene),0,EF_benign$case_freq_gene)


gnomAD_freq_gene<-aggregate(gnomAD_AF~gene,data=subset(cm_prediction,pathogenicity<=0.1 ),sum)
EF_benign$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$gene),]$gnomAD_AF
EF_benign$case_freq_gene<-ifelse(is.na(EF_benign$case_freq_gene),0,EF_benign$case_freq_gene)

EF_benign[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(EF_benign[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2])}))
EF_benign$EF<-ef(EF_benign$case_freq_gene,EF_benign$gnomAD_freq_gene,predict="benign")


EF_benign$ci_lower<-ef_ci_lower(EF_benign$case_freq_gene,EF_benign$gnomAD_freq_gene,patient_number,gnomAD_number,predict="benign")
EF_benign$ci_upper<-ef_ci_upper(EF_benign$case_freq_gene,EF_benign$gnomAD_freq_gene,patient_number,gnomAD_number,predict="benign")
#EF_benign$ci_upper<-ifelse(EF_benign$ci_upper>1,1,EF_benign$ci_upper)

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

EF_benign[,2:6]<-round(EF_benign[,2:6],2)
```

```{r, include=FALSE}
## EF with CardioBoost benign prediction excluding the ones seen in the training data


EF_benign_novel=data.frame(gene=gene_list)

case_freq_gene<-aggregate(case_freq~gene,data=subset(variant_count,pathogenicity<=0.1  & isTrain==FALSE),sum)
EF_benign_novel$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$gene),]$case_freq
EF_benign_novel$case_freq_gene<-ifelse(is.na(EF_benign_novel$case_freq_gene),0,EF_benign_novel$case_freq_gene)


gnomAD_freq_gene<-aggregate(gnomAD_AF~gene,data=subset(cm_prediction,pathogenicity<=0.1  & isTrain==FALSE),sum)
EF_benign_novel$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$gene),]$gnomAD_AF
EF_benign_novel$gnomAD_freq_gene<-ifelse(is.na(EF_benign_novel$gnomAD_freq_gene),0,EF_benign_novel$gnomAD_freq_gene)

EF_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(EF_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2])}))
EF_benign_novel$EF<-ef(EF_benign_novel$case_freq_gene,EF_benign_novel$gnomAD_freq_gene,predict="benign")

EF_benign_novel$ci_lower<-ef_ci_lower(EF_benign_novel$case_freq_gene,EF_benign_novel$gnomAD_freq_gene,patient_number,gnomAD_number,predict="benign")
EF_benign_novel$ci_upper<-ef_ci_upper(EF_benign_novel$case_freq_gene,EF_benign_novel$gnomAD_freq_gene,patient_number,gnomAD_number,predict="benign")

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

EF_benign_novel[,2:6]<-round(EF_benign_novel[,2:6],2)
```

```{r summary, echo=FALSE}

EF_compare<-data.frame(gene=gene_list,EF_raw=EF_raw$EF,EF_raw_ci=paste(EF_raw$ci_lower,EF_raw$ci_upper,sep=","),
                       EF_patho_novel=EF_patho_novel$EF,EF_patho_novel_ci=paste(EF_patho_novel$ci_lower,EF_patho_novel$ci_upper,sep=","),
                       EF_benign_novel=EF_benign_novel$EF,
                       EF_benign_novel_ci=paste(EF_benign_novel$ci_lower,EF_benign_novel$ci_upper,sep=","))

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

EF_compare<-EF_compare[order(EF_compare$EF_raw,decreasing = TRUE),]

EF_cardioboost<-subset(EF_compare,is.element(gene,sarc_gene))
EF_cardioboost

```