---
title: "Evaluation on hold-out test set"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_package, include=FALSE}
rm(list=ls())
library(dplyr)
library(mlr)
library(pROC)
library(cowplot)
library(precrec)
library(PRROC)
setwd("./")
source("../../../src/preprocess_test.R")
source("../../../src/permutation_test.R")
source("../../../src/predict.R")

load("../../../../data/cardiomyopathy_alternative/dcm/ml/train_ada.RData")
load("../../../../data/cardiomyopathy_alternative/dcm/preprocess.RData")
load("../../../../data/cardiomyopathy_alternative/dcm/dcm_holdout_test.RData")

```


```{r, include=FALSE}
##Prediction
test$pathogenic<-as.factor(test$pathogenic)
test_prediction<-predict.cardioboost(train_ada,test)
```

## Result


```{r, echo=FALSE}
### Predictive probablities distribution
p_ada<-data.frame(classifer="CardioBoost",prob_pathogenic=test_prediction$pathogenicity,class=test_prediction$pathogenic)
p_mcap<-data.frame(classifer="M-CAP",prob_pathogenic=test_prediction$MCAP,class=test_prediction$pathogenic)
p_revel<-data.frame(classifer="REVEL",prob_pathogenic=test_prediction$REVEL,class=test_prediction$pathogenic)

## Standard ML performance measures

##Use package precrec for interpolation calculation
score<-list(p_ada$prob_pathogenic,p_mcap$prob_pathogenic,p_revel$prob_pathogenic)
label<-p_ada$class
mmdat<-mmdata(score,label,modnames=c("CardioBoost","M-CAP","REVEL"))
sscurves<-evalmod(mmdat,raw_curves = TRUE)



#calculate the baseline precision: 

sscurves

```