---
title: "Evaluation of training models on Cardiomyopathy variants"
output: html_document
keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Environment, include=FALSE}
setwd("./")

rm(list=ls())
library(mlr)
library(precrec)

load("../../../data/cardiomyopathy/preprocess.RData")
load("../../../data/cardiomyopathy/train_scaled.RData")
load("../../../data/cardiomyopathy/ml/bmr_cart.RData")
load("../../../data/cardiomyopathy/ml/bmr_cvglmnet.RData")
load("../../../data/cardiomyopathy/ml/bmr_rf.RData")
load("../../../data/cardiomyopathy/ml/bmr_xgboost.RData")
load("../../../data/cardiomyopathy/ml/bmr_bartMachine.RData")
load("../../../data/cardiomyopathy/ml/bmr_gbm.RData")
load("../../../data/cardiomyopathy/ml/bmr_ada.RData")
load("../../../data/cardiomyopathy/ml/bmr_svm_RBF.RData")
load("../../../data/cardiomyopathy/ml/bmr_knn.RData")
```

 

```{r , echo=FALSE, message=FALSE, warning=FALSE}
## get the predicted class probablity

pred_cart<-bmr_cart_full$results$train$classif.rpart$pred
pred_glmnet<-bmr_cvglmnet_full$results$train$classif.cvglmnet.tuned$pred
pred_rf<-bmr_rf_full$results$train$classif.ranger.tuned$pred
pred_xgboost<-bmr_xgboost_full$results$train$classif.xgboost.tuned$pred
pred_bart<-bmr_bartMachine_full$results$train$classif.bartMachine.tuned$pred
pred_gbm<-bmr_gbm_full$results$train$classif.gbm.tuned$pred
pred_ada<-bmr_ada_full$results$train$classif.ada.tuned$pred
pred_svm<-bmr_svm_full$results$train$classif.ksvm.tuned$pred
pred_knn<-bmr_knn_full$results$train$classif.kknn$pred

generate_prob_dataframe<-function(classifier_name,prediction_object){

prob_data<-data.frame(classifier=classifier_name,prob_pathogenic=prediction_object$data$prob.1,class=prediction_object$data$truth)                     
return(prob_data)
}

p_cart<-generate_prob_dataframe("CART",pred_cart)
p_rf<-generate_prob_dataframe("RandomForest",pred_rf)
p_xgboost<-generate_prob_dataframe('xgboost',pred_xgboost)
p_ada<-generate_prob_dataframe('ada',pred_ada)
p_glmnet<-generate_prob_dataframe('glmnet',pred_glmnet)
p_bart<-generate_prob_dataframe('BART',pred_bart)
p_gbm<-generate_prob_dataframe('gbm',pred_gbm)
p_svm<-generate_prob_dataframe("SVM_RBF",pred_svm)
p_knn<-generate_prob_dataframe("KNN",pred_knn)

#the index of the rows in train_scaled
scaled_row<-pred_cart$data$id
#the index of the rows in the train_imputed
imputed_row<-match(train_scaled[scaled_row,]$key,train_imputed$key)

mcap_prob<-train_imputed[imputed_row,"MCAP"]
revel_prob<-train_imputed[imputed_row,"REVEL"]

p_mcap<-data.frame(classifer="M-CAP",prob_pathogenic=train_imputed[imputed_row,"MCAP"],class=train_imputed[imputed_row,]$pathogenic)
p_revel<-data.frame(classifer="REVEL",prob_pathogenic=train_imputed[imputed_row,"REVEL"],class=train_imputed[imputed_row,]$pathogenic)


```


## Calculate PRAUC and ROCAUC
```{r}
score<-list(p_glmnet$prob_pathogenic,p_cart$prob_pathogenic,p_rf$prob_pathogenic,p_bart$prob_pathogenic,p_xgboost$prob_pathogenic,p_gbm$prob_pathogenic,p_ada$prob_pathogenic,p_knn$prob_pathogenic,p_svm$prob_pathogenic,p_mcap$prob_pathogenic,p_revel$prob_pathogenic)
label<-p_cart$class

mmdat<-mmdata(score,label,modnames=c("GLMNET","CART","RF","BART","XGBOOST","GBM","ADA","KNN","SVM","MCAP","REVEL"))

sscurves<-evalmod(mmdat)

aucs <- auc(sscurves)
aucs_prc <- subset(aucs, curvetypes == "PRC")
aucs_prc$aucs<-round(aucs_prc$aucs,2)*100
knitr::kable(aucs_prc)

prc_auc<-aucs_prc$aucs

aucs_roc <- subset(aucs, curvetypes == "ROC")
aucs_roc$aucs<-round(aucs_roc$aucs,2)*100
knitr::kable(aucs_roc)

roc_auc<-aucs_roc$aucs
```
## Calculate Brier score

```{r}
br<-c(
measureBrier(p_glmnet$prob_pathogenic,p_glmnet$class,0,1),
measureBrier(p_cart$prob_pathogenic,p_cart$class,0,1),
measureBrier(p_rf$prob_pathogenic,p_rf$class,0,1),
measureBrier(p_bart$prob_pathogenic,p_bart$class,0,1),
measureBrier(p_xgboost$prob_pathogenic,p_xgboost$class,0,1),
measureBrier(p_gbm$prob_pathogenic,p_gbm$class,0,1),
measureBrier(p_ada$prob_pathogenic,p_ada$class,0,1),
measureBrier(p_knn$prob_pathogenic,p_knn$class,0,1),
measureBrier(p_svm$prob_pathogenic,p_svm$class,0,1),
measureBrier(p_mcap$prob_pathogenic,p_mcap$class,0,1),
measureBrier(p_revel$prob_pathogenic,p_revel$class,0,1))

Brier_score=round(br,2)
knitr::kable(data.frame(Classifier=c("GLMNET","CART","RF","BART","XGBoost","GBM","AdaBoost","SVM","KNN","MCAP","REVEL"),Brier_score))


```

## Calculate F1-measure

```{r, include=TRUE}

TPR<-c(measureTPR(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.90,1,0),1),measureTPR(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.90,1,0),1),measureTPR(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.90,1,0),1),measureTPR(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.90,1,0),1),measureTPR(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.90,1,0),1),measureTPR(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.90,1,0),1),measureTPR(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.90,1,0),1),measureTPR(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.90,1,0),1),measureTPR(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.90,1,0),1),
measureTPR(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.90,1,0),1),
measureTPR(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.90,1,0),1))

TPR
PPV<-c(measurePPV(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.90,1,0),1),measurePPV(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.90,1,0),1),measurePPV(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.90,1,0),1),measurePPV(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.90,1,0),1),measurePPV(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.90,1,0),1),measurePPV(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.90,1,0),1),measurePPV(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.90,1,0),1),measurePPV(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.90,1,0),1),measurePPV(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.90,1,0),1),
measurePPV(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.9,1,0),1),
measurePPV(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.9,1,0),1))
PPV

FPR<-c(measureFPR(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.90,1,0),0,1),measureFPR(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.90,1,0),0,1),
measureFPR(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.90,1,0),0,1),
measureFPR(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.90,1,0),0,1))
FPR

TNR<-c(measureTNR(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.10,1,0),0),measureTNR(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.10,1,0),0),measureTNR(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.10,1,0),0),measureTNR(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.10,1,0),0),measureTNR(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.10,1,0),0),measureTNR(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.10,1,0),0),measureTNR(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.10,1,0),0),measureTNR(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.10,1,0),0),measureTNR(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.10,1,0),0),
measureTNR(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.10,1,0),0),
measureTNR(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.10,1,0),0))
TNR

NPV<-c(measureNPV(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.10,1,0),0),measureNPV(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.10,1,0),0),measureNPV(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.10,1,0),0),measureNPV(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.10,1,0),0),measureNPV(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.10,1,0),0),measureNPV(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.10,1,0),0),measureNPV(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.10,1,0),0),measureNPV(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.10,1,0),0),measureNPV(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.10,1,0),0),
measureNPV(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.10,1,0),0),
measureNPV(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.10,1,0),0))
NPV

FNR<-c(measureFNR(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.10,1,0),0,1),measureFNR(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.10,1,0),0,1),
measureFNR(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.10,1,0),0,1),
measureFNR(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.10,1,0),0,1))
FNR


F1_measure<-round(2/((1/TPR)+(1/PPV)),2)
classifier<-c("GLMNET","CART","RF","BART","XGBOOST","GBM","AdaBoost","KNN","SVM","MCAP","REVEL")
pr_clin<-data.frame(classifier=classifier,TPR=TPR,PPV=PPV,FPR=FPR,TNR=TNR,NPV=NPV,FNR=FNR,F1_measure=F1_measure)

knitr::kable(pr_clin)

```

## Calculating MCC measure
```{r}
MCC<-c(measureMCC(p_glmnet$class,ifelse(p_glmnet$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_cart$class,ifelse(p_cart$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_rf$class,ifelse(p_rf$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_bart$class,ifelse(p_bart$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_xgboost$class,ifelse(p_xgboost$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_gbm$class,ifelse(p_gbm$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_ada$class,ifelse(p_ada$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_knn$class,ifelse(p_knn$prob_pathogenic>=0.90,1,0),0,1),measureMCC(p_svm$class,ifelse(p_svm$prob_pathogenic>=0.90,1,0),0,1),
measureMCC(p_mcap$class,ifelse(p_mcap$prob_pathogenic>=0.90,1,0),0,1),
measureMCC(p_revel$class,ifelse(p_revel$prob_pathogenic>=0.90,1,0),0,1))


MCC<-round(MCC,2)

```


## Supplementary Table 7
```{r}
eval_result<-data.frame(Classifier=classifier,PRAUC=prc_auc,ROCAUC=roc_auc,Brier_Score=Brier_score,MCC=MCC)
knitr::kable(eval_result)

####
#Conclusion: AdaBoost is selected as the best model
####

```

